"""Integration tests against the actual committed deliverables (titanic.csv,
the saved joblib pipeline) rather than synthetic fixtures -- catches issues
that only show up in the real generated artifacts, not just the logic that
produces them."""
import pathlib

import pandas as pd
import pytest

from src.cleaning import clean_titanic
from src.persist import load_pipeline, predict_on_raw

ANALYTICS_ROOT = pathlib.Path(__file__).resolve().parents[1]
CSV_PATH = ANALYTICS_ROOT / "titanic.csv"
MODEL_PATH = ANALYTICS_ROOT / "models" / "best_titanic_classifier.joblib"

pytestmark = pytest.mark.skipif(not CSV_PATH.exists(), reason="titanic.csv not yet generated by 01_eda.ipynb")


class TestCommittedCSV:
    def test_csv_loads_and_has_expected_shape_and_columns(self):
        df = pd.read_csv(CSV_PATH)
        assert len(df) == 891
        for col in ["survived", "pclass", "sex", "age", "sibsp", "parch", "fare", "embarked"]:
            assert col in df.columns

    def test_csv_is_the_raw_uncleaned_frame(self):
        """titanic.csv must be the RAW frame (with missing values still
        present) -- the offline fallback for sns.load_dataset, not an
        already-cleaned frame -- so clean_titanic has real work to do on it."""
        df = pd.read_csv(CSV_PATH)
        assert df["age"].isna().sum() > 0
        assert "deck" in df.columns  # only removed by clean_titanic, not before

    def test_clean_titanic_runs_on_the_committed_csv_without_error(self):
        df = pd.read_csv(CSV_PATH)
        clean = clean_titanic(df)
        assert clean.isna().sum().sum() == 0
        assert len(clean) >= 850  # only a couple of rows should ever be dropped


@pytest.mark.skipif(not MODEL_PATH.exists(), reason="model not yet saved by 02_modeling.ipynb")
class TestCommittedModel:
    def test_saved_pipeline_loads_and_predicts_on_raw_data(self):
        pipe = load_pipeline(MODEL_PATH)
        raw_row = pd.DataFrame(
            [{"pclass": 2, "sex": "female", "age": 25, "sibsp": 0, "parch": 0, "fare": 20.0, "embarked": "S"}]
        )
        preds = predict_on_raw(pipe, raw_row)
        assert preds[0] in (0, 1)

    def test_saved_pipeline_handles_missing_values_in_raw_input(self):
        pipe = load_pipeline(MODEL_PATH)
        raw_row = pd.DataFrame(
            [{"pclass": 3, "sex": "male", "age": None, "sibsp": 0, "parch": 0, "fare": None, "embarked": None}]
        )
        preds = predict_on_raw(pipe, raw_row)
        assert preds[0] in (0, 1)
