"""End-to-end runner: scrape -> clean -> load into SQLite -> run SQL queries ->
verify pd.read_sql / pd.merge equivalence -> write a query-output report.

Usage:
    python pipeline.py
"""
from __future__ import annotations

import pathlib

import pandas as pd

from src.clean import clean_dataframe
from src.db import build_database, get_connection
from src.queries import QUERIES, run_all_queries, merge_equivalent_top_rated_per_category
from src.scrape import scrape_categories

ROOT = pathlib.Path(__file__).resolve().parent
DATA_DIR = ROOT / "data"
DB_PATH = DATA_DIR / "zepto_books.db"
RAW_CSV = DATA_DIR / "books_raw.csv"
CLEAN_CSV = DATA_DIR / "books_clean.csv"
QUERY_REPORT = DATA_DIR / "query_output.md"


def main() -> None:
    DATA_DIR.mkdir(exist_ok=True)

    print("Step 1/6: scraping books.toscrape.com ...")
    raw_rows = scrape_categories()
    raw_df = pd.DataFrame(raw_rows)
    raw_df.to_csv(RAW_CSV, index=False)
    print(f"  scraped {len(raw_df)} rows -> {RAW_CSV}")

    print("Step 2/6: cleaning ...")
    clean_df = clean_dataframe(raw_df)
    report = clean_df.attrs["cleaning_report"]
    clean_df.to_csv(CLEAN_CSV, index=False)
    print(f"  cleaning report: {report}")
    print(f"  {len(clean_df)} clean rows -> {CLEAN_CSV}")
    assert len(clean_df) >= 60, "Expected at least 60 clean rows"
    assert clean_df["category"].nunique() >= 3, "Expected at least 3 categories"

    print("Step 3/6: building SQLite schema + loading data ...")
    build_database(clean_df, str(DB_PATH))
    print(f"  database written -> {DB_PATH}")

    print("Step 4/6: running SQL queries ...")
    conn = get_connection(str(DB_PATH))
    results = run_all_queries(conn)

    print("Step 5/6: verifying pd.read_sql vs pd.merge equivalence for the JOIN query ...")
    books_df = pd.read_sql("SELECT * FROM books;", conn)
    categories_df = pd.read_sql("SELECT * FROM categories;", conn)
    sql_join_result = results["top_5_rated_books_per_category"]
    merge_result = merge_equivalent_top_rated_per_category(books_df, categories_df)
    equivalent = sql_join_result.reset_index(drop=True).equals(merge_result.reset_index(drop=True))
    print(f"  pd.read_sql JOIN result equals pd.merge result: {equivalent}")
    assert equivalent, "pd.read_sql and pd.merge results diverged"

    print("Step 6/6: writing query output report ...")
    with open(QUERY_REPORT, "w", encoding="utf-8") as f:
        f.write("# SQL Query Output\n\n")
        f.write("Generated by `pipeline.py`. Each query is shown with its SQL and printed result.\n\n")
        for name, sql in QUERIES.items():
            df = results[name]
            f.write(f"## `{name}`\n\n```sql\n{sql.strip()}\n```\n\n")
            f.write(f"Rows returned: {len(df)}\n\n")
            f.write(df.head(15).to_markdown(index=False))
            f.write("\n\n")

        f.write("## pd.read_sql vs pd.merge equivalence (JOIN query)\n\n")
        f.write("`pd.read_sql` result (first 10 rows):\n\n")
        f.write(sql_join_result.head(10).to_markdown(index=False))
        f.write("\n\n`pd.merge` result on in-memory DataFrames (first 10 rows):\n\n")
        f.write(merge_result.head(10).to_markdown(index=False))
        f.write(f"\n\n**Equivalent (full result sets, all rows): {equivalent}**\n")

    conn.close()
    print(f"  report written -> {QUERY_REPORT}")
    print("\nDone.")


if __name__ == "__main__":
    main()
